tablePrefix: "scheduler_"
secretKey: "b956160659554dbcb0ae65e2f7d5de14"
port: 3000

web:
  title: Scheduler
  desc: 简单，开箱即用的分布式定时任务平台
  logo:
  avatar:

log:
  retain: 10
  interval: 30
  work: 10


mail:
  host: smtp.qq.com
  port: 465
  username: eininst@qq.com
  password: xxcccxx@#
  work: 5

  cc:
    - eininst@qq.com
    - eininst@aliyun.com

---
profile: dev

redis:
  addr: xxxxx.redis.zhangbei.rds.aliyuncs.com:6379
  db: 0
  poolSize: 100
  minIdleCount: 20
  username: default
  password: 7c3cD505

mysql:
  dsn: xx:xx@tcp(xxxxxxx:3306)/nft?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleCount: 32
  maxOpenCount: 128
  maxLifetime: 7200